name: CI Pipeline - SITasks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Criar arquivo .env temporário
        run: |
          touch ./backend/.env
          echo "MONGO_URI=mongodb://localhost:27017/test" >> ./backend/.env
          echo "SENDGRID_API_KEY=test_key" >> ./backend/.env

      - name: Testar Orquestração com Docker Compose
        run: |
          docker compose up --build -d
        
          # Tempo para os serviços Flask e Nginx subirem
          sleep 15
        
          docker ps
            
          # Verifica se os containers estão rodando
          if [ $(docker ps -q -f status=running | wc -l) -lt 2 ]; then
            echo "Erro: Um ou mais containers pararam de rodar."
            docker compose logs
            exit 1
          fi

      - name: Encerrar ambiente de teste
        if: always()
        run: docker compose down

      - name: Login no Docker Hub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build e Push da Imagem do Backend
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/dockerfile
          push: true
          tags: vitornayann/trab-backend:latest

      - name: Build e Push da Imagem do Frontend
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/dockerfile
          push: true
          tags: vitornayann/trab-frontend:latest